#!/bin/bash
# Script to display CSV file locations and help with download

echo "=========================================="
echo "📁 CSV Files Ready for Download"
echo "=========================================="
echo ""
echo "Files location: /home/user/Home555-TH/"
echo ""
echo "📊 CNC_Data.csv"
ls -lh /home/user/Home555-TH/CNC_Data.csv
echo "   - 100 machine records"
echo "   - Columns: ID, Machine ID, Machine Name, Status, Operation Type, Speed, Feed Rate, Temperature, X, Y, Z, Program Name, Timestamp, Date/Time"
echo ""
echo "📝 EPR_Records.csv"
ls -lh /home/user/Home555-TH/EPR_Records.csv
echo "   - 30 production records"
echo "   - Columns: ID, Production Order, Part Number, Part Name, Quantity, Machine ID, Operator, Start/End Time, Status, Quality Score, Defect Count, Notes, AI Analysis, Date/Time"
echo ""
echo "=========================================="
echo "📥 How to Download:"
echo "=========================================="
echo ""
echo "Method 1: VS Code / Codespaces"
echo "  1. Open File Explorer (left sidebar)"
echo "  2. Navigate to /home/user/Home555-TH/"
echo "  3. Right-click on CNC_Data.csv → Download"
echo "  4. Right-click on EPR_Records.csv → Download"
echo ""
echo "Method 2: Terminal Download"
echo "  1. Click the file links below"
echo "  2. Save the contents to your local machine"
echo ""
echo "Method 3: View in Browser"
echo "  Run: cat CNC_Data.csv"
echo "  Run: cat EPR_Records.csv"
echo "  Then copy/paste the content"
echo ""
echo "=========================================="
echo "Full file paths:"
echo "/home/user/Home555-TH/CNC_Data.csv"
echo "/home/user/Home555-TH/EPR_Records.csv"
echo "=========================================="
